{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vogue.component",
    "module": "RetrofitUrlManager",
    "version": "v1.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RetrofitUrlManager-v1.0.18.aar",
          "url": "RetrofitUrlManager-v1.0.18.aar",
          "size": 18319,
          "sha512": "778ac7338ec0528072ec2094d797791d4b667070b607f1147ae78c1705d81cc595acd72736d68b3349a79640eadfb18ec23f8e14fffe7736ba2fe688ffa3797e",
          "sha256": "3c4eb8db2db29b1a8061fd7d13f57baec4cbc3fa23450415412d146268d11f90",
          "sha1": "8b9c8b271470c2513d8cb82fe8b6510e2bd18982",
          "md5": "988191f33850c802351c70e78c1fc160"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "RetrofitUrlManager-v1.0.18.aar",
          "url": "RetrofitUrlManager-v1.0.18.aar",
          "size": 18319,
          "sha512": "778ac7338ec0528072ec2094d797791d4b667070b607f1147ae78c1705d81cc595acd72736d68b3349a79640eadfb18ec23f8e14fffe7736ba2fe688ffa3797e",
          "sha256": "3c4eb8db2db29b1a8061fd7d13f57baec4cbc3fa23450415412d146268d11f90",
          "sha1": "8b9c8b271470c2513d8cb82fe8b6510e2bd18982",
          "md5": "988191f33850c802351c70e78c1fc160"
        }
      ]
    }
  ]
}
